
    #1.应用配置
server:
  port: 9002
    #spring配置
spring:
  application:
    name: ihrm-system
      #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
      #3.jpa
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
jwt:
  config:
    key: saas-ihrm
    ttl: 3600000

    #注册到eureka的服务地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka/

ai:
  appId: 18894338
  apiKey: ujtwAxkmwuibwjRoh14DK2gQ
  secretKey: Vl0Tj3k0jLo9LZzoA7UaNdHuhQ7zp2dg
  imageType: BASE64
  groupId: itcast
qr:
  url: http://localhost:8080/#/facelogin



